### ISSUE TITLE
⚙️Configuración repositorio

### ISSUE THREAD

**Issue by konami12** [OrcaPracticas/workshop-next#1]
## 📝 Descripción

Como desarrollador quiero realizar la configuración inicial correspondiente al repositorio

### 📋 Tareas

- [x] Crear archivo `.gitignore`
- [x] Crear `Readme.md`
- [x] Crear `Licencia`
- [x] Generar la rama `Develop`
- [x] Crear Templates de Issues

**Comment by konami12** [comment]
Configuración base terminada

**Comment by konami12** [comment]
Tareas completadas
